name = "cloudflare-b2"
main = "src/index.js"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

#[vars]
#B2_APPLICATION_KEY_ID = "<your b2 application key id>"
#B2_ENDPOINT = "<your endpoint - e.g. s3.us-west-001.backblazeb2.com >"
#BUCKET_NAME = "<your bucket name, $path, or $host>"
#ALLOW_LIST_BUCKET = "<true, if you want to allow clients to list objects, otherwise false>"
#RCLONE_DOWNLOAD = "<true, if you are using the Worker to proxy downloads for rclone, otherwise false>"
